# 通过yml配置文件自定义用户名密码（不推荐使用）
#spring:
#  security:
#    user:
#      name: admin
#      password: admin
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 指定数据库连接池（默认会检查到此连接池）
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动
    url: jdbc:mysql://127.0.0.1:3306/security?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true # 连接地址
    username: root # 用户名
    password: 123 # 密码
    hikari:
      # 连接池常用配置
      auto-commit: true # 自动提交（默认true）
      connection-timeout: 30000 # 连接超时时间（单位：毫秒）（默认值：30秒）
      idle-timeout: 600000 # 连接在池中闲置的最长时间（单位：毫秒）（默认值：10分钟）
      max-lifetime: 900000 # 池中连接的最长生命周期（单位：毫秒）（默认值：30分钟）
      maximum-pool-size: 10 # 池达到的最大大小，包括空闲和使用中的连接（默认值：10）
      minimum-idle: 5 # 池中维护的最小空闲连接数（默认值：与maximum-pool-size相同）
